# Generated by Django 5.0.3 on 2024-04-08 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("professor", "0002_alter_professor_cpf"),
    ]

    operations = [
        migrations.CreateModel(
            name="Oficina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(null=True)),
                (
                    "fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oficinas",
                        to="professor.professor",
                    ),
                ),
            ],
        ),
    ]
