# Generated by Django 5.0.3 on 2024-08-07 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Oficina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(null=True)),
                ("workload", models.DecimalField(decimal_places=2, max_digits=5)),
                ("city_of_realization", models.CharField(max_length=100)),
                ("creation_date", models.DateField(auto_now_add=True)),
                ("date_of_realization", models.DateField()),
                ("time_of_realization", models.TimeField()),
                ("realized", models.BooleanField(default=False)),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oficinas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
