# Generated by Django 5.0.3 on 2024-08-07 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aluno", "0001_initial"),
        ("oficina", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Presenca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("presente", models.BooleanField(default=False)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presencas",
                        to="aluno.aluno",
                    ),
                ),
                (
                    "oficina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presencas",
                        to="oficina.oficina",
                    ),
                ),
            ],
            options={
                "unique_together": {("aluno", "oficina")},
            },
        ),
    ]
