# Generated by Django 5.0.3 on 2024-08-07 17:03

import aluno.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "cpf",
                    models.CharField(
                        help_text="Informe um CPF com exatamente 11 dígitos.",
                        max_length=11,
                        unique=True,
                        validators=[aluno.models.validate_cpf_length],
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
