# Generated by Django 5.0.3 on 2024-04-04 19:41

import professor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professor",
            name="cpf",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[professor.models.validate_cpf_length],
            ),
        ),
    ]
